# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lottes Blog
email:
description: >
  Geschichten Ã¼ber alles und jeden. Kritik. Liebe. Vernunft.
  Schokolade.
baseurl: ""
url: "http://lotterei.github.io"
twitter_username:
github_username:

# Build settings
markdown: kramdown
